import "@/styles/main.scss";
import localFont from "next/font/local";

const Gotham = localFont({
  src: [
    {
      path: "fonts/Gotham/Gotham-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "fonts/Gotham/Gotham-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "fonts/Gotham/Gotham-Book.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/Gotham/Gotham-Light.woff2",
      weight: "300",
      style: "normal",
    },
  ],
});
const ChronicleDisplay = localFont({
  src: [
    {
      path: "fonts/ChronicleDisplay/ChronicleDisplay-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "fonts/ChronicleDisplay/ChronicleDisplay-Semi.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "fonts/ChronicleDisplay/ChronicleDisplay-Roman.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/ChronicleDisplay/ChronicleDisplay-LightItalic.woff2",
      weight: "300",
      style: "normal",
    },
  ],
});

export const metadata = {
  title: "Schumacher",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      style={{
        "--ff-chronicle-display": ChronicleDisplay.style.fontFamily,
        "--ff-gotham": Gotham.style.fontFamily,
      }}
    >
      <body className={Gotham.className}>{children}</body>
    </html>
  );
}
